# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
