# Generated by Django 2.2.27 on 2023-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20181119_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='request_id',
            field=models.CharField(max_length=255, db_index=True),
        ),
    ]